# TUI selector application

TUI_SELECTOR_VERSION = 540706fb7d026f2abab2dc1bf91054810ba53e11
TUI_SELECTOR_SITE = https://github.com/antmicro/tui-selector
TUI_SELECTOR_SITE_METHOD = git
TUI_SELECTOR_GIT_SUBMODULES = YES

TUI_SELECTOR_INSTALL_STAGING = YES
TUI_SELECTOR_INSTALL_TARGET = YES

TUI_SELECTOR_LICENSE = Apache-2.0

TUI_SELECTOR_DEPENDENCIES = ncurses

$(eval $(cmake-package))
