#!/bin/sh
#
# Starts Xorg
#

BIN=/usr/bin/xinit
PIDFILE=/var/run/xorg.pid

start() {
	printf "Starting Xorg: "
	cp /etc/X11/xinit/xinitrc $HOME/.xinitrc
	start-stop-daemon -S -q -b -m -p $PIDFILE --exec $BIN
	[ $? = 0 ] && sleep 3 && echo "OK" || echo "FAIL"
}

stop() {
	printf "Stopping Xorg: "
	start-stop-daemon -K -q -p $PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	sleep 2
	start
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	restart|reload)
		restart
	;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
