# NVIDIA

LIBNVIDIA_CONTAINER_VERSION = v1.0.2
LIBNVIDIA_CONTAINER_SITE = $(call github,NVIDIA,libnvidia-container,$(LIBNVIDIA_CONTAINER_VERSION))
LIBNVIDIA_CONTAINER_LICENSE = BSD-3-Clause
LIBNVIDIA_CONTAINER_LICENSE_FILES = LICENSE

define LIBNVIDIA_CONTAINER_BUILD_CMDS
    cd $(@D) && \
    ARCH="$(HOSTARCH)" DESTDIR="$(TARGET_DIR)" WITH_SECCOMP=no make install prefix=/usr
endef

$(eval $(generic-package))
