# NVIDIA

LIBNVIDIA_CONTAINER_VERSION = v1.4.0
LIBNVIDIA_CONTAINER_SITE = $(call github,NVIDIA,libnvidia-container,$(LIBNVIDIA_CONTAINER_VERSION))
LIBNVIDIA_CONTAINER_LICENSE = Apache-2.0
LIBNVIDIA_CONTAINER_LICENSE_FILES = LICENSE

LIBNVIDIA_CONTAINER_DEPENDENCIES += libcap
LIBNVIDIA_CONTAINER_CFLAGS += -DEXTENDED_ATTRIBUTES
LIBNVIDIA_CONTAINER_LDFLAGS += -lcap

$(eval $(generic-package))
