PYTHON_SERVIS_VERSION = 1e120b8be5a6c4f849fffe630a3f5e36474545ae
PYTHON_SERVIS_SITE = $(call github,antmicro,servis,$(PYTHON_SERVIS_VERSION))
PYTHON_SERVIS_SETUP_TYPE = setuptools
PYTHON_SERVIS_LICENSE = Apache-2.0
PYTHON_SERVIS_LICENSE_FILES = LICENSE

$(eval $(python-package))
